### ISSUE TITLE
Regarding to the Knee MRI data

### ISSUE THREAD

**Issue by TDBaker2016** [tmquan/RefineGAN#1]
The method achieved impressive performance on the CS-MRI task. And I'd like to know how to use the Knee datasets originally from mridata.org? The knee data shown here is in tif format. However, the downloaded data format from the website is in clf, using the readReconData.m provided by the author, I obtained the k-space data with multiple coil a dimension, I guess. So how can I have the MR images based on these k-space data? Using Bart toolbox from Berkeley?
Looking forward your helpful reply!

**Comment by tmquan** [comment]
Yes, they were extracted using BART toolbox. 
There are several examples that can help you to extract images from clf. 
This link might be very helpful https://mrirecon.github.io/bart/examples.html
