### ISSUE TITLE
I have some questions about the images generated by the reconstruction.

### ISSUE THREAD

**Issue by Alxemade** [tmquan/RefineGAN#2]
Hello, I run you code on the github, but  I have some questions about it.  First,  why do you set DIMZ  = 2 in your code, [RefineGAN/Utils.py](https://github.com/Alxemade/RefineGAN/blob/master/Utils.py), is that means the netword you create is complex? Second I follow your running steps and run your code on my own datasets, but the reconstruction is comfusing.  ![image](https://github.com/Alxemade/screenshots/raw/master/20180827/Selection_001.png)
 the shape is (1,2,256,3072)what the number meaning?

Also,  ![image](https://github.com/Alxemade/screenshots/raw/master/20180827/Selection_002.png)

the tiff image is unormal, I can't understant.I was hoping you could help me with this problem, I can't get it right.

**Comment by Alxemade** [comment]
Hi@tmquan,
    Thank you for your answer! You say the brain data is used for magnitude-value experiment  and the  knees data is used for complex-value experiment. Here, I run my own MRI datasets and have already make sure the data range is in between 0~255, the shape is (255,255), which is real-value image not the complex image, should I need to use 2-channel image and set the DIMZ = 2? Also, if I have the MRI datasets which the training datasets size is 15000, I doubt the training time is too long for me, need I change which code to fit my datasets?

**Comment by Alxemade** [comment]
Hi,  My training data likes this, 
![image](https://github.com/Alxemade/Screenshots/raw/master/20180827/Selection_003.png), is that ok?
My  brain training data is png image, and generate test image is tiff image, I can not show the tiff image correctly, can you help me how to generate the png image instead of png image?
```
for idx, o in enumerate(pred.get_result()):
		print pred
		print len(o)
		print o[0].shape

		outA = o[0][:, :, :, :] 

	
		colors0 = np.array(outA) #.astype(np.uint8)
		head, tail = os.path.split(filenames[idx])
		tail = tail.replace('png', 'tif')
		print tail
		print colors0.shape
		print colors0.dtype
		import skimage.io
	
		skimage.io.imsave(resultDir+ "/full_"+tail, np.squeeze(colors0[...,256*1:256*2])) # Zerofill
		skimage.io.imsave(resultDir+"/zfill_"+tail, np.squeeze(colors0[...,256*2:256*3])) # Zerofill
		skimage.io.imsave(resultDir+tail, np.squeeze(colors0[...,256*4:256*5])) # Zerofill

		skimage.io.imsave(resultDir+"mag/mag_"+tail, np.abs(np_complex(np.squeeze(colors0[...,256*4:256*5]))))
		skimage.io.imsave(resultDir+"ang/ang_"+tail, np.angle(np_complex(np.squeeze(colors0[...,256*4:256*5]))))


		skimage.io.imsave(resultDir+"/M/mag/mag_"+tail, np.abs(np_complex(np.squeeze(colors0[...,256*2:256*3]))))
		skimage.io.imsave(resultDir+"/M/ang/ang_"+tail, np.angle(np_complex(np.squeeze(colors0[...,256*2:256*3]))))

```
Should I change where?

**Comment by Alxemade** [comment]
The scales :+1:
 ![image](https://github.com/Alxemade/Screenshots/raw/master/20180828/Selection_003.png)

The reconstructions:
 ![image](https://github.com/Alxemade/Screenshots/raw/master/20180828/Selection_004.png)
 ![image](https://github.com/Alxemade/Screenshots/raw/master/20180828/Selection_005.png)
 ![image](https://github.com/Alxemade/Screenshots/raw/master/20180828/Selection_006.png)

**Comment by tmquan** [comment]
As you can see, the reconstruction is fine according to the tensorboard. 
In order to view the image by your viewer, you have to cast color0 to np.uint8 or use Fiji/ImageJ to open tif files.

**Comment by Alxemade** [comment]
Thank you for answering my question all the time. I download the imagej and show the image correctly!
 ![image](https://github.com/Alxemade/Screenshots/raw/master/20180828/Selection_008.png). Follow you advice, I use `colors0 = np.array(outA).astype(np.uint8)`, and the reconstruction image type is unit8, so how can I to presever the image in png format?  If I remove the code `tail = tail.replace('png', 'tif')` is wrong?What is the role of this code?

**Comment by tmquan** [comment]
Since I have to make the quantitative evaluation, I would save the image in np.float32 and only tif format in skimage.io can preserve this. The role of that line of code is just changing the format. 

If you quantize to np.uint8, then the source of errors will increase which you do not want to. 

I will close this issue for now. Thank you for your feedback.
